// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

#include "./common.hpp"
#include "./common_examples.hpp"

#include <aas_core/aas_3_1/stringification.hpp>
#include <aas_core/aas_3_1/types.hpp>

#define CATCH_CONFIG_MAIN
#include <catch2/catch.hpp>

namespace aas = aas_core::aas_3_1;

const std::filesystem::path& DetermineLogDir() {
  static aas::common::optional<std::filesystem::path> result;
  if (!result.has_value()) {
    result = test::common::DetermineTestDataDir() / "XxxOrDefault";
  }

  return *result;
}

TEST_CASE("Test ValueTypeOrDefault on a min. Extension") {
  const std::shared_ptr<
    aas::types::IExtension
  > instance(
    test::common::examples::LoadMinExtension()
  );

  const std::filesystem::path log_path(
    DetermineLogDir()
      / "Extension.ValueTypeOrDefault.min.log"
  );

  const std::string serialized(
    aas::stringification::to_string(
      instance->ValueTypeOrDefault()
    )
  );

  test::common::AssertContentEqualsExpectedOrRecord(
    serialized,
    log_path
  );
}

TEST_CASE("Test ValueTypeOrDefault on a max. Extension") {
  const std::shared_ptr<
    aas::types::IExtension
  > instance(
    test::common::examples::LoadMaxExtension()
  );

  const std::filesystem::path log_path(
    DetermineLogDir()
      / "Extension.ValueTypeOrDefault.max.log"
  );

  const std::string serialized(
    aas::stringification::to_string(
      instance->ValueTypeOrDefault()
    )
  );

  test::common::AssertContentEqualsExpectedOrRecord(
    serialized,
    log_path
  );
}

TEST_CASE("Test KindOrDefault on a min. Qualifier") {
  const std::shared_ptr<
    aas::types::IQualifier
  > instance(
    test::common::examples::LoadMinQualifier()
  );

  const std::filesystem::path log_path(
    DetermineLogDir()
      / "Qualifier.KindOrDefault.min.log"
  );

  const std::string serialized(
    aas::stringification::to_string(
      instance->KindOrDefault()
    )
  );

  test::common::AssertContentEqualsExpectedOrRecord(
    serialized,
    log_path
  );
}

TEST_CASE("Test KindOrDefault on a max. Qualifier") {
  const std::shared_ptr<
    aas::types::IQualifier
  > instance(
    test::common::examples::LoadMaxQualifier()
  );

  const std::filesystem::path log_path(
    DetermineLogDir()
      / "Qualifier.KindOrDefault.max.log"
  );

  const std::string serialized(
    aas::stringification::to_string(
      instance->KindOrDefault()
    )
  );

  test::common::AssertContentEqualsExpectedOrRecord(
    serialized,
    log_path
  );
}

TEST_CASE("Test KindOrDefault on a min. Submodel") {
  const std::shared_ptr<
    aas::types::ISubmodel
  > instance(
    test::common::examples::LoadMinSubmodel()
  );

  const std::filesystem::path log_path(
    DetermineLogDir()
      / "Submodel.KindOrDefault.min.log"
  );

  const std::string serialized(
    aas::stringification::to_string(
      instance->KindOrDefault()
    )
  );

  test::common::AssertContentEqualsExpectedOrRecord(
    serialized,
    log_path
  );
}

TEST_CASE("Test KindOrDefault on a max. Submodel") {
  const std::shared_ptr<
    aas::types::ISubmodel
  > instance(
    test::common::examples::LoadMaxSubmodel()
  );

  const std::filesystem::path log_path(
    DetermineLogDir()
      / "Submodel.KindOrDefault.max.log"
  );

  const std::string serialized(
    aas::stringification::to_string(
      instance->KindOrDefault()
    )
  );

  test::common::AssertContentEqualsExpectedOrRecord(
    serialized,
    log_path
  );
}

TEST_CASE("Test OrderRelevantOrDefault on a min. SubmodelElementList") {
  const std::shared_ptr<
    aas::types::ISubmodelElementList
  > instance(
    test::common::examples::LoadMinSubmodelElementList()
  );

  const std::filesystem::path log_path(
    DetermineLogDir()
      / "SubmodelElementList.OrderRelevantOrDefault.min.log"
  );

  const std::string serialized(
    std::to_string(
      instance->OrderRelevantOrDefault()
    )
  );

  test::common::AssertContentEqualsExpectedOrRecord(
    serialized,
    log_path
  );
}

TEST_CASE("Test OrderRelevantOrDefault on a max. SubmodelElementList") {
  const std::shared_ptr<
    aas::types::ISubmodelElementList
  > instance(
    test::common::examples::LoadMaxSubmodelElementList()
  );

  const std::filesystem::path log_path(
    DetermineLogDir()
      / "SubmodelElementList.OrderRelevantOrDefault.max.log"
  );

  const std::string serialized(
    std::to_string(
      instance->OrderRelevantOrDefault()
    )
  );

  test::common::AssertContentEqualsExpectedOrRecord(
    serialized,
    log_path
  );
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
